from typing import List, Literal
from pydantic import BaseModel, Field


class SupervisorOutput(BaseModel):
    output_type: Literal[
        "plan",
        "thought",
        "supervisor_final_answer",
        "hallucination",
        "no_hallucination",
        "SQL Agent",
        "Analysis Agent",
        "Visualization Agent",
    ] = Field(
        ...,
        description="Supervisor control signal: planning/thinking steps, agent names, 'supervisor_final_answer', or hallucination audit outputs.",
    )
    output_content: str = Field(..., description="Content corresponding to the chosen output.")


class SQLAgentOutput(BaseModel):
    """
    Structured response for the minimal SQL controller loop.
    """

    output_type: Literal[
        "plan",
        "thought",
        "summarize_datastore_updates",
        "execute_sql",
        "persist_dataset",
        "sql_agent_final_answer",
        "hallucination",
        "no_hallucination",
    ] = Field(
        ...,
        description="Control signal emitted by the SQL controller.",
    )
    output_content: str = Field(..., description="Reasoning or instruction associated with the current step.")
    sql_query: str | None = Field(
        default=None,
        description="SQL to run when output_type == 'execute_sql'.",
    )
    reference_key: str | None = Field(
        default=None,
        description="Datastore key to use when output_type == 'persist_dataset'.",
    )
    description: str | None = Field(
        default=None,
        description="Datastore description to use when output_type == 'persist_dataset'.",
    )


class AnalysisAgentOutput(BaseModel):
    """Structured response produced by the analysis agent."""

    analysis_agent_final_answer: str = Field(
        ...,
        description="Narrative summary that references datastore keys, row counts, and caveats.",
    )
    insights: List[str] = Field(
        default_factory=list,
        description="Bullet-style insights derived from the provided data.",
    )
    follow_up_questions: List[str] = Field(
        default_factory=list,
        description="Suggested next questions or actions for the supervisor.",
    )
    referenced_keys: List[str] = Field(
        default_factory=list,
        description="Datastore keys that were essential for the analysis.",
    )

class VisualizationFigurePlan(BaseModel):
    """Specification for a single figure to render."""

    chart_intent: str = Field(
        default="",
        description="Brief natural-language summary describing the requested chart.",
    )
    chart_type: Literal[
        "line",
        "area",
        "bar",
        "stacked_bar",
        "scatter",
        "histogram",
        "box",
        "heatmap",
        "step",
        "rolling_line",
    ] = Field(
        default="line",
        description="Recommended chart family.",
    )
    dataset_hints: List[str] = Field(
        default_factory=list,
        description="Keywords or reference hints to find the right dataset.",
    )
    metric_keywords: List[str] = Field(
        default_factory=list,
        description="Measurements or metrics mentioned in the request.",
    )
    entity_keywords: List[str] = Field(
        default_factory=list,
        description="Gateways, sites, or categorical filters referenced by the user.",
    )
    time_window: str = Field(
        default="",
        description="Natural-language description of the requested time scope.",
    )
    priority_notes: str = Field(
        default="",
        description="Additional constraints or reminders for the controller.",
    )


class VisualizationPlanOutput(BaseModel):
    """High-level visualization intent generated by the LLM."""

    overall_intent: str = Field(
        default="",
        description="Brief overall summary describing the requested visuals.",
    )
    figures: List[VisualizationFigurePlan] = Field(
        default_factory=list,
        description="List of figure specs to render.",
    )
    max_figures: int = Field(
        default=3,
        description="Maximum number of figures to generate.",
    )
    max_metrics_per_figure: int = Field(
        default=3,
        description="Maximum number of metrics per figure.",
    )
    max_entities_per_figure: int = Field(
        default=8,
        description="Maximum number of series categories per figure.",
    )
    priority_notes: str = Field(
        default="",
        description="Additional constraints or reminders for the controller.",
    )
    chart_intent: str = Field(
        default="",
        description="Legacy single-chart intent summary.",
    )
    chart_type: Literal[
        "line",
        "area",
        "bar",
        "stacked_bar",
        "scatter",
        "histogram",
        "box",
        "heatmap",
        "step",
        "rolling_line",
    ] = Field(
        default="line",
        description="Legacy single-chart type.",
    )
    dataset_hints: List[str] = Field(
        default_factory=list,
        description="Legacy dataset hints for single-chart flow.",
    )
    metric_keywords: List[str] = Field(
        default_factory=list,
        description="Legacy metric keywords for single-chart flow.",
    )
    entity_keywords: List[str] = Field(
        default_factory=list,
        description="Legacy entity keywords for single-chart flow.",
    )
    time_window: str = Field(
        default="",
        description="Legacy time window for single-chart flow.",
    )


class VisualizationCodeOutput(BaseModel):
    """LLM-produced Python code for visualization execution."""

    code: str = Field(
        ...,
        description="Python code to execute for generating visualizations.",
    )
    summary: str = Field(
        default="",
        description="Short summary of what the code produces.",
    )
    notes: str = Field(
        default="",
        description="Optional implementation notes or caveats.",
    )


__all__ = [
    "SupervisorOutput",
    "SQLAgentOutput",
    "AnalysisAgentOutput",
    "VisualizationPlanOutput",
    "VisualizationFigurePlan",
    "VisualizationCodeOutput",
]
